export enum IconEnum {
    ARROW_DOWN = 'ARROW_DOWN',
    ARROW_RIGHT_DOWN = 'ARROW_RIGHT_DOWN',
    ARROW_RIGHT_UP = 'ARROW_RIGHT_UP',
    DASHBOARD = 'DASHBOARD',
    NEWS = 'NEWS',
    CLOSE = 'CLOSE'
}
