FROM node:20.11.0-alpine as builder

WORKDIR /build
COPY ../package.json ../package-lock.json ./
RUN npm install

COPY ../ ./

RUN npm run build:scrapper

EXPOSE 3001

CMD ["npm", "run", "start:scrapper"]