FROM node:16-alpine3.18 as builder

WORKDIR /build
COPY ../package.json ../package-lock.json ./
RUN npm install

COPY ../ ./

COPY . .
RUN npm run build:data

EXPOSE 3000

CMD ["npm", "run", "start:data"]