FROM node:16-alpine3.18 as builder

WORKDIR /build
COPY ../package.json ../package-lock.json ./
RUN npm install

COPY ../ ./

RUN npm run build:scrapper

EXPOSE 3001

CMD ["npm", "run", "start:scrapper"]