export enum KafkaTopicEnum {
    BINANCE_DATA_PROCESSING = 'BINANCE_DATA_PROCESSING',
    BINANCE_DATA_BACKUP = 'BINANCE_DATA_BACKUP',
    RSS_FEED_PROCESSING = 'RSS_FEED_PROCESSING',
    RSS_FEED_BACKUP = 'RSS_FEED_BACKUP'
}
