version: '3.8'
services:
  scrapper:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.Scrapper
    ports:
      - '3001:3001'
  data:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.Data
    ports:
      - '3000:3000'

