version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080